# Generated by Django 5.0.6 on 2025-04-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successwebsite', '0002_gallery_homecontent_shop_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='file_name',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='audio',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
