# Generated by Django 5.0.6 on 2025-04-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successwebsite', '0003_remove_audio_file_name_audio_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='epic_moment',
            field=models.ImageField(null=True, upload_to='epic_moment/'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='youtube_vid',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='products_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='products_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_items',
            field=models.ImageField(null=True, upload_to='shop_item/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_photos',
            field=models.ImageField(null=True, upload_to='tour_photos'),
        ),
        migrations.AddField(
            model_name='tour',
            name='venue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
