# Generated by Django 5.0.6 on 2025-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('successwebsite', '0004_homecontent_epic_moment_homecontent_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_photos',
            field=models.ImageField(null=True, upload_to='tour_photos/'),
        ),
    ]
