# Generated by Django 5.2.6 on 2025-10-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('successwebsite', '0005_alter_tour_tour_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_photos',
        ),
    ]
